server:
  port: 8763
foo: wecome to github respo2 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
spring: 
  rabbitmq: 
    host: 192.168.43.227
    port: 15672
    username: admin
    password: admin
  cloud: 
    bus: 
      enabled: true
      trace: 
        enabled: true
management: 
  endpoints: 
    web: 
      exposure: 
        include: bus-refresh       
